# Script mode: writes the current local time as macros. Re-run on every build so
# an incremental build cannot ship a stale stamp. Invoked with -DHEADER=<path>.

string(TIMESTAMP STAMP_YEAR "%Y")
string(TIMESTAMP STAMP_MONTH "%m")
string(TIMESTAMP STAMP_DAY "%d")
string(TIMESTAMP STAMP_HOUR "%H")
string(TIMESTAMP STAMP_MINUTE "%M")
string(TIMESTAMP STAMP_SECOND "%S")

# Leading zeros would read as octal in C, so strip them.
foreach(field STAMP_MONTH STAMP_DAY STAMP_HOUR STAMP_MINUTE STAMP_SECOND)
    string(REGEX REPLACE "^0([0-9])" "\\1" ${field} "${${field}}")
endforeach()

set(CONTENT "/* Generated by cmake/build_stamp.cmake - do not edit. */
#pragma once
#define BUILD_STAMP_YEAR   ${STAMP_YEAR}
#define BUILD_STAMP_MONTH  ${STAMP_MONTH}
#define BUILD_STAMP_DAY    ${STAMP_DAY}
#define BUILD_STAMP_HOUR   ${STAMP_HOUR}
#define BUILD_STAMP_MINUTE ${STAMP_MINUTE}
#define BUILD_STAMP_SECOND ${STAMP_SECOND}
")

if(EXISTS "${HEADER}")
    file(READ "${HEADER}" OLD_CONTENT)
else()
    set(OLD_CONTENT "")
endif()

if(NOT OLD_CONTENT STREQUAL CONTENT)
    file(WRITE "${HEADER}" "${CONTENT}")
endif()
