#include "build_time.h"

/* Preferred source is build_stamp.h, regenerated by CMake on every build.
 * Without it (standalone compile) fall back to this file's own compile time:
 * __DATE__ is "MMM DD YYYY" (day space-padded), __TIME__ is "HH:MM:SS". */
#if defined(__has_include)
#if __has_include("build_stamp.h")
#include "build_stamp.h"
#endif
#endif

namespace {

    constexpr uint8_t digit(char c) { return (uint8_t)(c == ' ' ? 0 : (c - '0')); }

    constexpr uint8_t two_digits(const char *s) { return (uint8_t)(digit(s[0]) * 10 + digit(s[1])); }

    /* Distinguishes months by the letters that are unique among them:
     * Jan/Jun/Jul share 'J', Mar/May share 'M', Apr/Aug share 'A'. */
    constexpr uint8_t month_of(const char *m) {
        return m[0] == 'J'   ? (m[1] == 'a' ? 1 : (m[2] == 'n' ? 6 : 7))
               : m[0] == 'F' ? 2
               : m[0] == 'M' ? (m[2] == 'r' ? 3 : 5)
               : m[0] == 'A' ? (m[1] == 'p' ? 4 : 8)
               : m[0] == 'S' ? 9
               : m[0] == 'O' ? 10
               : m[0] == 'N' ? 11
                             : 12;
    }

    constexpr uint16_t year_of(const char *d) {
        return (uint16_t)(digit(d[7]) * 1000 + digit(d[8]) * 100 + digit(d[9]) * 10 + digit(d[10]));
    }

#ifdef BUILD_STAMP_YEAR
    constexpr BuildStamp kStamp = {
        BUILD_STAMP_YEAR, BUILD_STAMP_MONTH, BUILD_STAMP_DAY, BUILD_STAMP_HOUR, BUILD_STAMP_MINUTE, BUILD_STAMP_SECOND,
    };
#else
    constexpr BuildStamp kStamp = {
        year_of(__DATE__),    month_of(__DATE__),       two_digits(__DATE__ + 4),
        two_digits(__TIME__), two_digits(__TIME__ + 3), two_digits(__TIME__ + 6),
    };
#endif

} // namespace

BuildStamp build_stamp(void) { return kStamp; }
